export const downloadPDF = (elementId, title = 'Diagnosis Report') => {
  const element = document.getElementById(elementId);
  if (!element) return;

  const originalTitle = document.title;
  document.title = title;

  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow pop-ups to print the report.');
    return;
  }

  const styles = document.querySelectorAll('link[rel="stylesheet"], style');
  let stylesHTML = '';
  styles.forEach(style => {
    if (style.tagName === 'LINK') {
      stylesHTML += `<link rel="stylesheet" href="${style.href}">`;
    } else {
      stylesHTML += `<style>${style.innerHTML}</style>`;
    }
  });

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
      <head>
        <title>${title}</title>
        ${stylesHTML}
        <style>
          body { padding: 20px; font-family: system-ui, -apple-system, sans-serif; }
          .no-print { display: none !important; }
          button, .print-hide { display: none !important; }
          @media print {
            body { margin: 0; padding: 0; }
            .page-break { page-break-before: always; }
          }
        </style>
      </head>
      <body>
        ${element.outerHTML}
        <div class="print-hide" style="text-align:center; margin-top:30px; font-size:12px; color:#aaa;">
          Generated by MedExpert AI – Medical Diagnosis Assistant
        </div>
      </body>
    </html>
  `);

  printWindow.document.close();
  printWindow.print();
  printWindow.onafterprint = () => {
    printWindow.close();
    document.title = originalTitle;
  };
};